env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules: 
  react/prop-types: 0
  quotes: 
    - 2
    - single
    - avoidEscape: true 

