name: ci

on:
  release:
    types:
      - created

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - 
        name: Get latest tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: moficodes/ibmcloud-kubernetes-admin  # The repository to scan.
          releases-only: true  # We know that all relevant tags have a GitHub release for them.
        id: tag  # The step ID to refer to later.
      -
        name: build-and-push-kubeadmin
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile.web
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kubeadmin:${{ steps.tag.outputs.tag }}
